config/routes.rb
Rails.application.routes.draw do

  root :to => 'homepages#index'
  resources :user_sessions
  resources :teams
  resources :games
  resources :players
  resources :homepages
  resources :venues

  get 'home' => 'homepages#index', :as => :home

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/game.rb
class Game < ActiveRecord::Base
	belongs_to :venue
	has_many :players
	has_many :teams, through: :players

	def pretty_booked_from
		booked_from.strftime("%I:%M %p")
	end

	def pretty_booked_till
		booked_till.strftime("%I:%M %p")
	end

	def remaining_challengers
		p = players.where(is_owner: false).count
		required_teams - p
	end

	def is_owner(current_user)
		Team.find(players.where(is_owner: true).first.team_id) == current_user
	end

	def owner
		players.where(is_owner: true).first
	end

	def is_challenger(team)
		challenger = players.where(is_owner: false).map {|player| player.team}
		challenger.include?(team)
	end

	def challengers
		players.where(is_owner: false)
		# Team.find_all(players.where(is_owner: false).pluck(:team_id))
	end

	def venue_open
		v = Venue.find(12)
		v.open_time.strftime("%I").to_i
	end

	def venue_close
		v = Venue.find(12)
		v.close_time.strftime("%I").to_i
	end
end

app/models/player.rb
class Player < ActiveRecord::Base
	belongs_to :team
	belongs_to :game
end

app/models/team.rb
class Team < ActiveRecord::Base
	authenticates_with_sorcery!

	validates :password, length: { minimum: 3 }
	validates :password, confirmation: true
	validates :password_confirmation, presence: true

	validates :email, uniqueness: true

	has_many :games, through: :players
	has_many :players

	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
	authenticates_with_sorcery!

	validates :password, length: { minimum: 3 }
	validates :password, confirmation: true
	validates :password_confirmation, presence: true

	validates :email, uniqueness: true

	has_many :games, through: :players
	has_many :players

	mount_uploader :image, ImageUploader
end

app/models/venue.rb
class Venue < ActiveRecord::Base
	has_many :games

	geocoded_by :address
	after_validation :geocode, if: :address_changed?

	def pretty_open_time
		open_time.strftime("%I:%M %p")
	end

	def pretty_close_time
		close_time.strftime("%I:%M %p")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :require_login

  private
  def not_authenticated
  	redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

	def index
		@games = Game.all
		@game = Game.new
	end

	def show
		@game = Game.find(params[:id])
	end

	def new
		@game = Game.new
	end

	def create
		@game = Game.new(game_params)

		if @game.save
			@player = Player.new(team: current_user, game: @game, is_owner: true)
			if @player.save
				redirect_to game_path(@game)
			else
				render 'new'
			end
		else
			render 'new'
		end
	end

	def edit
		@game = Game.find(params[:id])
	end

	def update
		@game = Game.find(params[:id])

		if @game.update_attributes(game_params)
			redirect_to game_path(@game)
		else
			render 'edit'
		end
	end

	private
	def game_params
		params.require(:game).permit(:title, :booked_from, :booked_till, :venue_id, :required_teams)
	end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
	skip_before_filter :require_login

	def index
		@games = Game.all
		@game = Game.new
		@teams = Team.all
		@team = Team.new
	end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	def new
		@player = Player.new
	end

	def create
		@player = Player.new(player_params)
		@game = @player.game
		@owner = @game.players.where(is_owner: true).first

		if @player.save
			UserMailer.matchup_email(@owner, @player).deliver

			redirect_to games_path
		else
			redirect_to games_path
		end
	end

	def player_params
		params.require(:player).permit(:team_id, :game_id, :is_owner)
	end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
	skip_before_filter :require_login, only: [:index, :new, :create]
	before_filter :initializeGame

	def show
		@team = Team.find(params[:id])
	end

	def new
		@team = Team.new
	end

	def create
		@team = Team.new(team_params)
		if @team.save
			#UserMailer.welcome_email(@team).deliver

			auto_login(@team)
			redirect_to games_path, :notice => "Successfully signed up"
		else
			render 'new', :notice => "Error signing up"
		end
	end

	def edit
		@team = Team.find(params[:id])
	end

	def update
		@team = Team.find(params[:id])
		if @team.update_attributes(team_params)
			redirect_to team_path(@team)
		else
			render 'edit'
		end
	end

	private

	def team_params
		params.require(:team).permit(:email, :name, :location, :password, :password_confirmation, :image)
	end

	def initializeGame
		@game = Game.new
	end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
	skip_before_filter :require_login, except: [:destroy]

	def new
		@team = Team.new
	end

	def create
		if @team = login(params[:email], params[:password])
			redirect_back_or_to(:games)
		else
			flash.now[:alert] = 'Login failed. Try again'
			render 'new'
		end
	end

	def destroy
		logout
		redirect_to(:home, notice: 'Logged out!')
	end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
	skip_before_filter :require_login
	
	def new
		@venue = Venue.new
	end

	def create
		@venue = Venue.new(venue_params)

			if @venue.save
				redirect_to venue_path(@venue)
			else
				render 'new'
			end
	end

	def index
		@venues = if params[:search]
			Venue.near(params[:search], 1, units: :km)
		elsif params[:latitude] && params[:longitude]
			Venue.near([params[:latitude], params[:longitude]], 1, units: :km)
		else
			Venue.all
		end

		respond_to do |format|
			format.html
			format.js
		end
	end

	def show
		@venue = Venue.find(params[:id])
	end

	private
	def venue_params
		params.require(:venue).permit(:name, :address, :open_time, :close_time)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/games/_form.html.erb
<% @venue = Venue.find(1) %>
<% @venue.close_time.strftime("%I").to_i %>
<% @venue.open_time.strftime("%I").to_i %>

<% @game ||= Game.new %>
<%= form_for @game do |f| %>
<form>
	<div class="row">
		<div class="large-12 columns">
			<label>Title
				<%= f.text_field :title %>
			</label>
		</div>
	</div>

	<div class="row">
		<div class="large-12 columns">
			<label>Select Venue
				<%= collection_select(:game, :venue_id, Venue.all, :id, :name, prompt: true) %>
			</label>
		</div>
	</div>

	<div class="row">
		<div class="large-4 columns">
			<label>From
				<%= f.time_select :booked_from, {start_hour: @venue.open_time.strftime("%k").to_i , end_hour: @venue.close_time.strftime("%k").to_i, minute_step: 30, ampm: true} %>
			</label>
		</div>
	</div>

	<div class="row">
		<div class="large-4 columns">
			<label>To
				<%= f.time_select :booked_till, {start_hour: @venue.close_time.strftime("%k").to_i , end_hour: @venue.close_time.strftime("%k").to_i, minute_step: 30, ampm: true} %>
			</label>
		</div>
	</div>

	<div class="row">
		<div class="large-4 columns">
			<label>Required teams
				<%= f.number_field :required_teams %>
			</label>
		</div>
	</div>

	<div>
		<%= f.submit %>
	</div>
	<% end %>
</form>

app/views/games/_game.html.erb
<% @games.each do |game| %>
<ul class="small-block-grid-1 medium-block-grid-1 large-block-grid-1 text-center">

	<% unless current_user.nil? %>
	<% if game.remaining_challengers > 0 %>
	<li class="a">
		<div class="games">
			<% if game.is_owner(current_user) %><span class="round alert label">Your match</span><% end%>
			<h4> <%= link_to game.title, game_path(game) %> <%#= game.owner.team.email %> </h4>
			<p> <%= game.pretty_booked_from %> - <%= game.pretty_booked_till %> </p>
			<p> At: <%= link_to game.venue.name, venue_path(game.venue) %> </p>
			<p>Teams Required: <%= game.required_teams %></p>
			Spots left: <% game.remaining_challengers.times do %>
			<img src="https://s3-us-west-2.amazonaws.com/kikomatchup/soccer.png">
			<% end %>
		</div>
		<% if game.is_owner(current_user) %>
		<% elsif game.is_challenger(current_user) %>
		<span style="font-size: 20px" class="success label round reply">MatchUP email sent. Waiting for reply</span>
		<% else %>
		<%= button_to "MatchUP", players_path(:player => {team_id: current_user.id, game_id: game.id, is_owner: false }), {:class => "button round success matchup" } %>
		<% end %>
	</li>
	<% end %>
	<% end %>
</ul>
<% end %>

app/views/games/index.html.erb
<div class="background">
	<%= render 'game' %>
</div>

app/views/games/show.html.erb
<div class="games">
	<div> <h1 class="title"> <%= @game.title %> </h1></div>
	<p>Time: <%= @game.pretty_booked_from %> TO <%= @game.pretty_booked_till %> </p>
	<p> Place: <%= @game.venue.name %> </p>
	<p>Address: <%= @game.venue.address %> </p>
	<p>Teams Required: <%= @game.required_teams %></p>
	Spots left: <% @game.remaining_challengers.times do %>
	<img src="https://s3-us-west-2.amazonaws.com/kikomatchup/soccer.png">
	<% end %>
	<h3 class="challengers">Challengers</h3>
	<% @game.challengers.each do |c| %>
	<%= link_to c.team.name, team_path(c.team.id) %><br/>
	<% end %>
</div>

app/views/homepages/index.html.erb
<%= render 'user_sessions/form' %>

<div id="homepage">
	<div id="intro">
		<h2> Welcome to MatchUP </h2>
		<p>MatchUP is a Football (soccer) matching app. It makes it easier for teams to find others to play with. Have a venue already booked? Perfect!. Log in, create a new game with the time, venue and how many teams you need and you are good to go.</p>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Matchup</title>
  <link rel="stylesheet" href="assets/animate.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{Rails.application.secrets.google_maps_api}" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>
<div id="backgroundmain"></div>

  <div class="fixed">
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><a href=""><%= link_to "MatchUP", games_path %></a></h1>
        </li>
         <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <% if current_user %>
        <ul class="right">
          <li><%= link_to "Edit Profile", edit_team_path(current_user.id) %></li>
          <li><%= link_to "Logout", :logout, method: :post %></li>
        </ul>
        <ul class="right">
          <li class="active"><%= link_to current_user.email, team_path(current_user) %></li>
        </ul>
        <ul class="left">
          <li><%= link_to "All Available games", games_path %></li>
          <li></li>
        </ul>
        <ul class="left">
          <li> <%= link_to 'All venues', venues_path %> </li>
        </ul>
        <ul class="left">
          <li>
            <div id="myModal" class="reveal-modal small" data-reveal>
              <div> <%= render 'games/form' %> </div>
              <a class="close-reveal-modal">&#215;</a>
            </div>

            <a href="" data-reveal-id="myModal">Have a game?</a>
          </li>
        </ul>
        <% else %>
        <ul class="right">
          <li>
            <div id="myModal" class="reveal-modal small" data-reveal>
              <div> <%= render 'teams/form' %> </div>
              <a class="close-reveal-modal">&#215;</a>
            </div>

            <a href="" data-reveal-id="myModal">Register</a>
          </li>
          <li><a id="login">Login</a></li>
        </ul>
        <% end %>
      </section>
    </nav>
  </div>


  <div>
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
  </div>

  <%= yield %>
</body>
</html>

app/views/user_sessions/_form.html.erb
<div id="animated-example" class="animated fadeInDownBig reg-form">
  <%= form_tag user_sessions_path, :method => :post do %>
  <p>  <%= text_field_tag :email, nil , placeholder: "Username" %></p>
  <p>  <%= password_field_tag :password, nil, placeholder: "Password" %> </p>
    <%= submit_tag "Login", class: 'button success round' %>
  <% end %>
</div>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<%= render 'form' %>

<%#= link_to 'Back', games_path %>

app/views/users/_form.html.erb
<% @user ||= User.new %>
<%= form_for @user do |f| %>
<form>
   <div class="row">
     <div class="large-4 columns">
      <label>Email: 
       <%= f.text_field :email, placeholder: 'Email' %>
    </label>
 </div>
</div>
<div class="row">
  <div class="large-4 columns">
   <label>Username: 
    <%= f.text_field :name, placeholder: 'Username' %>
 </label>
</div>
</div>
<div class="row">
  <div class="large-4 columns">
   <label>Location: 
    <%= f.text_field :location, placeholder: 'Location' %>
 </label>
</div>
</div>
<div class="row">
  <div class="large-4 columns">
   <label>Password:
    <%= f.password_field :password, placeholder: 'Password' %>
 </label>
</div>
<div class="large-4 columns">
   <label>Password confirmation:
    <%= f.password_field :password_confirmation, placeholder: 'Password confirmation' %>
 </label>
</div>
<%= f.file_field :image %>
</div>

<%= f.submit %>
<% end %>
</form>

app/views/venues/_form.html.erb
<%= form_for @venue do |f| %>
<div>
	<%= f.label :name %> <br/>
	<%= f.text_field :name %>
</div>

<div>
	<%= f.label :address %>
	<%= f.text_field :address %>
</div>

<div>
	Open time: <%= f.time_select :open_time, {start_hour: @venue.open_time , end_hour: @venue.close_time, discard_minute: true, ampm: true} %>
	Close time:<%= f.time_select :close_time, {start_hour: @venue.open_time , end_hour: @venue.close_time, discard_minute: true, ampm: true} %>
</div>

<div>
	<%= f.submit %>
</div>
<% end %>

app/views/venues/_venue.html.erb
<table>
  <thead>
    <tr>
      <th width="200">Venue name</th>
      <th width="600">Address</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= link_to venue.name, venue_path(venue) %></td>
      <td><%= venue.address %></td>
    </tr>
  </tbody>
</table>

app/views/venues/index.html.erb
<% venue_array = @venues.map{|v| [v.name, v.address, v.pretty_open_time, v.pretty_close_time, v.latitude.to_f, v.longitude.to_f, venue_path(v)]} %>

<%= content_tag "div","",id: "locations", data: {venues: venue_array, allvenues: true} %>

<div id="map-canvas"></div>



<a href=""></a>

<%= form_tag venues_path, id: "venue_search", method: :get do %>
<%= label_tag :search, 'Find venues by address' %>
<%= text_field_tag :search, params[:search] %>
<%= submit_tag 'submit', class: 'button success' %>
<% end %>






<button id="current-location">Filter by nearby</button>


<div id="venues">
  <%= render @venues %>
</div>

app/views/venues/index.js.erb
$('#venues').html('<%= j(render @venues) %>');

app/views/venues/new.html.erb
<h1>Create a venue</h1>

<%= render 'form' %>

app/views/venues/show.html.erb
<div class="page-title">
	<h1><%= @venue.name %> Venue</h1>
</div>

<div>
	<p class="page-title">Address: <%= @venue.address %> </p>
	<%= content_tag "div","", id: "map-canvas", data: {latitude: @venue.latitude.to_f, longitude: @venue.longitude.to_f} %>
</div>

<h2 class="page-title">Games in this venue</h2>

<ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-2 text-center">
	<% @venue.games.each do |game| %>
	<% unless current_user.nil? %>
	<% if game.remaining_challengers > 0 %>
	<li>
		<div class="games">
			<% if game.is_owner(current_user) %><span class="round alert label">Your match</span><% end%>
			<p> <%= game.title %> </p>
			<p> BY: <%= link_to game.owner.team.name, team_path(game.owner) %> </p>
			<p>Time: <%= game.pretty_booked_from %> - <%= game.pretty_booked_till %> </p>
			<p>Teams Required: <%= game.required_teams %></p>
			Spots left: <% game.remaining_challengers.times do %>
			<img src="https://s3-us-west-2.amazonaws.com/kikomatchup/soccer.png">
			<% end %>
		</div>
		<% if game.is_owner(current_user) %>
		<%elsif game.is_challenger(current_user) %>
		<span style="font-size: 20px" class="success round label">MatchUP email sent</span>
		<% else %>
		<h3 class="challengers">Challengers</h3>
		<% game.challengers.each do |c| %>
		<%= link_to c.team.email, team_path(c.team.id) %><br/>
		<% end %>
		<%= button_to "MatchUP", players_path(:player => {team_id: current_user.id, game_id: game.id, is_owner: false }), {:class => "button round success matchup" } %>
		<% end %>
	</li>
	<% end %>
	<% end %>
	<% end %>
</ul>